### ISSUE TITLE
pyyaml vulnerability

### ISSUE THREAD

**Issue by tombaker** [tombaker/mklists#8]
See https://github.com/tombaker/mklists/network/alert/requirements.txt/pyyaml/open

**Comment by nishad** [comment]
https://pypi.org/project/ruamel.yaml/ is the most versatile, fast and actively maintained YAML parser/emitter for Python, supports YAML 1.2.

**Comment by tombaker** [comment]
@nishad Thanks!  I switched to `ruamel.yaml` and it passes all tests - see [diff](https://github.com/tombaker/mklists/commit/a306354667fdc12cfed311cd8edfe219f06f3b0e).

Much appreciated!

**Comment by tombaker** [comment]
However, Scrutinizer flags a problem, with the error message: `ModuleNotFoundError: No module named 'ruamel'`.  Can you advise?

**Comment by nishad** [comment]
`ruamel.yaml` should be installed as a new package, so I assume it is missing from the requirements. But it may be present in the development environment as a dependency of some other installed package.

**Comment by tombaker** [comment]
@Nishad T R <rimpoche@gmail.com> Please excuse my ignorance...  I installed
it in the virtual development that I use for development.  Do I also need
to update my configuration, for example [requirements.txt](
https://github.com/tombaker/mklists/blob/master/requirements.txt)?

**Comment by nishad** [comment]
@tombaker, I believe Scrutinizer installs dependencies into a virtual environment [1]. In the absence of a  `.scrutinizer.yml` file, it may try to install dependencies from `requirements.txt`. So it is better to add `ruamel.yaml` to `requirements.txt`.

[1] https://scrutinizer-ci.com/docs/guides/python/continuous-integration-deployment

**Comment by tombaker** [comment]
@nishad Thanks!  I have done this and it appears to have fixed the problem.  Closing the issue...
